chore: fix build after #13338 merge caused compile error (#13345)
Following the merge of #13338, `forgejo` branch is [failing to build](https://codeberg.org/forgejo/forgejo/actions/runs/174924/jobs/0/attempt/1) with:
```
tests/integration/api_repo_file_helpers.go:1: : # forgejo.org/tests/integration [forgejo.org/tests/integration.test]
tests/integration/actions_trigger_test.go:1365:13: undefined: forgery
tests/integration/actions_trigger_test.go:1366:13: undefined: forgery
tests/integration/actions_trigger_test.go:1367:42: undefined: forgery (typecheck)
// Copyright 2019 The Gitea Authors. All rights reserved.
1 issues:
* typecheck: 1
exit status 1
Please run 'make lint-go-fix' and commit the result
make: *** [Makefile:494: lint-go] Error 1
⚙️ [runner]: exitcode '2': failure
```

Reviewed-on: https://codeberg.org/forgejo/forgejo/pulls/13345
Reviewed-by: Gusted <gusted@noreply.codeberg.org>