fix(tests): make JS sleep test not flaky (#14374)
I got this test failure:

```
 FAIL  web_src/js/utils.test.js > sleep
AssertionError: expected 1999 to be greater than or equal to 2000
 ❯ testSleep web_src/js/utils.test.js:197:27
    195|   const endTime = Date.now();    // Record the end time
    196|   const actualSleepTime = endTime - startTime;
    197|   expect(actualSleepTime).toBeGreaterThanOrEqual(ms);
       |                           ^
    198| }
    199|
 ❯ web_src/js/utils.test.js:189:3
```

This seems expected as there can be rounding differences between the start and end times, leading to this. Therefore I propose to relax this assertion

Reviewed-on: https://codeberg.org/forgejo/forgejo/pulls/14374
Reviewed-by: Gusted <gusted@noreply.codeberg.org>