chore(ci): run e2e tests and collect coverage (followup) (#13935)
Install playwright dependencies because they are missing in the CI image.

It [fails](https://codeberg.org/forgejo/forgejo/actions/runs/187005/jobs/0/attempt/3#jobstep-5-3780) with:

```sh
    Error: browserType.launch:
    ╔══════════════════════════════════════════════════════╗
    ║ Host system is missing dependencies to run browsers. ║
    ║ Missing libraries:                                   ║
    ║     libX11-xcb.so.1                                  ║
    ║     libXrandr.so.2                                   ║
    ║     libXcomposite.so.1                               ║
    ║     libXcursor.so.1                                  ║
    ║     libXdamage.so.1                                  ║
    ║     libXi.so.6                                       ║
    ║     libXfixes.so.3                                   ║
    ║     libgtk-3.so.0                                    ║
    ║     libgdk-3.so.0                                    ║
    ║     libatk-1.0.so.0                                  ║
    ║     libasound.so.2                                   ║
    ║     libdbus-1.so.3                                   ║
    ╚══════════════════════════════════════════════════════╝
```

This is not a problem in the `testing.yml` workflow because it uses an image with [those dependencies pre-installed](https://code.forgejo.org/forgejo/playwright-image-builder/src/commit/d3e48e627a5b790058a035fd8faf908266e3dc14/build-playwright/Dockerfile), exclusively for running the e2e tests.

Reviewed-on: https://codeberg.org/forgejo/forgejo/pulls/13935
Reviewed-by: Clouds <me@cloudsftp.de>