fix(ci): semgrep duplicate id (#14085)
In addtion, use validate before --test otherwise validation errors may be very cryptic. For instance:

```sh
$ semgrep validate .semgrep/config
[00.03][WARNING]: invalid rule .semgrep.config.unit-test-missing-setup-function, .semgrep/config/unit-test.yaml:9:9: Expected a string value for .semgrep.config.unit-test-missing-setup-function
```

versus:

```sh
$ semgrep --test .semgrep/tests/ --config .semgrep/config/
...
-------------------------------------------------------------------------------
The following config files produced errors:
	.semgrep/config/unit-test.yaml: Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/semgrep/test.py", line 313, in invoke_semgrep_multi
    output = semgrep.run_scan.run_scan_and_return_json(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/semgrep/run_scan.py", line 1757, in run_scan_and_return_json
    ) = run_scan(
        ^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/semgrep/telemetry.py", line 468, in inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/semgrep/simple_profiling.py", line 100, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/semgrep/run_scan.py", line 1447, in run_scan
    sanity_check_resolved_config(real_config_errors, configs_obj)
  File "/usr/lib/python3.12/site-packages/semgrep/run_scan.py", line 201, in sanity_check_resolved_config
    raise SemgrepError(
semgrep.error.SemgrepError: invalid configuration file found (1 configs were invalid)
```

### Compliance

- [x] I confirm that I make this contribution in accordance with [Forgejo's AI Agreement](https://codeberg.org/forgejo/governance/src/commit/9084720dc6a7fbf1d3f358919d46bd6adfb55287/AIAgreement.md).

Reviewed-on: https://codeberg.org/forgejo/forgejo/pulls/14085
Reviewed-by: Mathieu Fenniak <mfenniak@noreply.codeberg.org>