fix: build error from soft conflict between #13830 and #13513 (#13843)
Fixes `forgejo` branch is broken due to a soft conflict between API changes in #13513, and usage of that same API in #13830 merged afterwards:
```
routers/api/v1/repo/action.go:1: : # forgejo.org/routers/api/v1/repo [forgejo.org/routers/api/v1/repo.test]
routers/api/v1/repo/issue_lock.go:50:11: undefined: getIssueFromContext
routers/api/v1/repo/issue_lock.go:117:11: undefined: getIssueFromContext (typecheck)
// Copyright 2023 The Gitea Authors. All rights reserved.
routers/api/v1/user/key.go:18:2: could not import forgejo.org/routers/api/v1/repo (-: # forgejo.org/routers/api/v1/repo
routers/api/v1/repo/issue_lock.go:50:11: undefined: getIssueFromContext
routers/api/v1/repo/issue_lock.go:117:11: undefined: getIssueFromContext) (typecheck)
	"forgejo.org/routers/api/v1/repo"
	^
2 issues:
* typecheck: 2
exit status 1
```

Reviewed-on: https://codeberg.org/forgejo/forgejo/pulls/13843
Reviewed-by: limiting-factor <limiting-factor@noreply.codeberg.org>